all :
	gcc main_pi.c -o main_pi -L/usr/lib/python3.7/config-3.7m-arm-linux-gnueabihf -L/usr/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions -I/usr/include/python3.7m -I/usr/include/python3.7m -L../libs -lmynet -pthread -lm
